import Head from 'next/head';
import TopTutors from '../Components/HomePage/TopTutors';
import SearchPage from '../Components/SearchPage';

export default function Home() {
  return (
    <div className='bg-[#FFFDFD]'>
      <Head>
        <title>Search | Skilly Tree</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <SearchPage /> */}
      <TopTutors />

    </div>
  )
}